#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <sodium.h>
#include "efv_sha256.h"
#include "bss_utils.h"

int main(int argc, char *argv[])
{
    if (argc != 2) {
        fprintf(stderr, "Usage: %s <payload>\n", argv[0]);
        return -1;
    }

    const char *payload_path = argv[1];
    size_t msg_len = 0;
    uint8_t *msg = bss_read_file_to_dynamic_buffer(payload_path, &msg_len);
    if (!msg) {
        fprintf(stderr, "Error: failed to read payload\n");
        return -1;
    }

    uint8_t hash[EFV_SHA256_HASH_SIZE];

    if (sodium_init() < 0) {
        fprintf(stderr, "Failed to init libsodium\n");
        return -1;
    }
    if (crypto_hash_sha256(hash, msg, msg_len) != 0) {
        fprintf(stderr, "Error: SHA-256 hash failed\n");
        free(msg);
        return -1;
    }

    printf("SHA256 generated by sodium for: %s\n", payload_path);
    bss_print_hex_data("SHA256 : ", hash, EFV_SHA256_HASH_SIZE, EFV_SHA256_HASH_SIZE);

    if (efv_sha256_hash(hash, msg, msg_len) != 0) {
        fprintf(stderr, "Error: SHA-256 hash failed\n");
        free(msg);
        return -1;
    }

    printf("SHA256 generated by EFV_SHA256 for: %s\n", payload_path);
    bss_print_hex_data("SHA256 : ", hash, EFV_SHA256_HASH_SIZE, EFV_SHA256_HASH_SIZE);

    free(msg);
    return 0;
}